services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vector-voyager-ui
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
